### ISSUE TITLE
OOB - Does not finish 'Shards Install' (Kemal?)

### ISSUE THREAD

**Issue by sci-phi** [jasonl99/card_game#19]
Cloned per instructions and attempted to install dependencies:

```
*   5fc6705 GitHub 2017-03-01 15:21:11 -0500 Merge pull request #18 from jasonl99/events

card_game $ shards install
Updating https://github.com/askn/faker.git
Updating https://github.com/jasonl99/lattice-core.git
Updating https://github.com/jeromegn/slang.git
Updating https://github.com/kemalcr/kemal.git
git command failed: git tag --list --contains next --column=never (malformed object name next). Maybe a commit, branch or file doesn't exist?
```

Crystal 0.21.1 (2017-03-14) LLVM 4.0.0
Mac OS X 10.12.3

**Comment by jasonl99** [comment]
It looks like the dependency on the _next_ branch of kemal is the issue. I've changed that in lattice-core's shard.yml...could you try again?

**Comment by sci-phi** [comment]
It didn't seem to change anything, so I poked at it...

Shards file for 'card_game' references the 'events' branch of 'lattice-core', and the change you made seems only to be in 'master' branch there: 

```
   lattice-core:
     github: jasonl99/lattice-core
-    branch: events
+    branch: master
     # path: /home/jason/crystal/lattice-core
``` 

I tried manually editing the local shards.yml for card_game to use master which moved forward a bit but still ultimately failed. 

However, this time it advised me to try "shards update" and it finished the install after I did.
I was then able to run the app OK. 

Thanks!
